Repository wptide/wptide, pull requests merged in 2018-10, with the labels that each got.

#135 Set WP_DEBUG_LOG to true
  .gitignore
  service/api/tpl/wp-config.tpl
Labels: enhancement

#130 Change info after setup to edit /ets/hosts
  service/api/setup.sh
Labels: documentation

#160 Update ISSUE_TEMPLATE.md
  ISSUE_TEMPLATE.md
Labels: task
